server:
  port: 8080
  http2:
    enabled: true
# grpc client
grpc:
  client:
    mailServer:
      address: "static://localhost:9090"#"static://localhost:9090"
      negotiation-type: plaintext
spring:
  application:
    name: identity-service
  profiles:
    active: prod
# api versioning
  mvc:
    apiVersion:
      use:
        path-segment: 2
      supported: 1.0
      default: 1.0

#  env config
  config:
    import: optional:file:.env[.properties]
#  datasource config
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
api:
  base:
    path: /identity-service/api
otp:
  digit: 6
  ttl: 5m
  rate-limit-ttl: 15s
  block-ttl: 15m
  ip-rate-limit-ttl: 10s

# logging
logging:
  level:
    root: INFO
  structured:
    format:
      console: ecs
  file:
    name: identity-service-log.json

